# Workflow to mirror repo

name: Mirror
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  repo-sync:
    runs-on: self-hosted
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "ParkA-org/ParkA-WebApp"
        source_branch: "master"
        destination_repo: "Bant89/mirror-parka"
        destination_branch: "master"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
