# Workflow to mirror repo

name: Mirror
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sync-repo:
    runs-on: self-hosted
    steps:
    - name: cur-dir
      uses: actions/checkout@v2
    - name: sync-repo
      uses: ./
      with:
        source_repo: "ParkA-org/ParkA-WebApp"
        destination_repo: "Bant89/ParkA-Mirror"
        username: ${{ secrets.GIT_USER }}
        user_password: ${{ secrets.GIT_PASSWORD }}
